### ISSUE TITLE
Ember.js 1.11-beta support?

### ISSUE THREAD

**Issue by Kuzirashi** [DockYard/ember-validations#268]
Everything works great for me in Ember 1.10, but when I switch to Ember.js 1.11-beta(5) I can't display my server side errors using ember-forms, when applying extending from EV mixin. When I remove extending from it I can easily add errors to models. Are you aware of it and wait for Ember.js 1.11 to be released as stable or should I add my code here so it could be resolved now? Thanks in advance.

**Comment by bcardarella** [comment]
Do you get any stack trace?

**Comment by Kuzirashi** [comment]
I get `undefined is not a function` when I try to use `add` method of `model.errors`, I think it gets replaced by EmberMixin specific `errors` property.
![zrzut ekranu z 2015-03-12 18 08 01](https://cloud.githubusercontent.com/assets/4950658/6623397/f72dacec-c8e2-11e4-8ae4-49883a7aff3f.png)

**Comment by Kuzirashi** [comment]
Also, very important thing to note is that also `adapterDidInvalidate` in model.js fails to call `add` on `errors` property:
~~~~ JavaScript
  // FOR USE DURING COMMIT PROCESS

  /**
    @method adapterDidInvalidate
    @private
  */
  adapterDidInvalidate: function(errors) {
    var recordErrors = get(this, 'errors');
    for (var key in errors) {
      if (!errors.hasOwnProperty(key)) {
        continue;
      }
      recordErrors.add(key, errors[key]); # undefined is not a function, stack trace below
/*
TypeError: undefined is not a function
    at Ember.Object.extend.adapterDidInvalidate (model.js:1084)
    at Ember.Object.extend.recordWasInvalid (store.js:1263)
    at store.js:2074
    at tryCatch (ember.debug.js:46700)
    at invokeCallback (ember.debug.js:46712)
    at publish (ember.debug.js:46683)
    at publishRejection (ember.debug.js:46625)
    at ember.debug.js:27019
    at Queue.invoke (ember.debug.js:871)
    at Object.Queue.flush (ember.debug.js:936)
*/
    }
    this._saveWasRejected();
  },
~~~~

**Comment by mutewinter** [comment]
:+1: have this problem with Ember 1.11 beta 5 as well.

**Comment by mutewinter** [comment]
The core of the problem here is that Ember.Validations.Errors is overwriting the model instance's DS.Errors. This didn't happen until Ember 1.11 for us.

**Comment by mutewinter** [comment]
I fixed this, so far, by changing the name of the errors property:

```
export default Ember.Mixin.create(setValidityMixin, {
  init: function() {
    this._super();
    this.clientErrors = Errors.create();
```

Instead of `this.errors`.

**Comment by bcardarella** [comment]
@mutewinter I have bumped this up to the ember project. Would it be possible to get a small project that recreates the issue to help diagnose?

**Comment by stefanpenner** [comment]
are we confident this isn't an ember-data side regression?

Can someone provide me a repo that demonstrates this issue

**Comment by rwjblue** [comment]
> The core of the problem here is that Ember.Validations.Errors is overwriting the model instance's DS.Errors.

Seems like this might be an Ember Data issue (though I don't see changes to `DS.Model.prototype.errors` lately)?

**Comment by bcardarella** [comment]
I asked the author of the issue to provide a reproducible example

**Comment by stefanpenner** [comment]
`push` on an enumerable doesn't seem to be correct. I believe that should have been `pushObject`

**Comment by stefanpenner** [comment]
Ahh, i wonder if this is related to CP `descriptors` being moved form meta to the object, so that are more stomp-able.

**Comment by DiegeticShadow** [comment]
In case it helps anyone, this is how I got ember-validations 1.0.0 to work with Ember 1.11.1:

```
DS.Model.reopen
	# Based on https://github.com/emberjs/data/blob/v1.0.0-beta.16.1/packages/ember-data/lib/system/model/model.js#L1121
	adapterDidInvalidate: (errors) ->
		recordErrors = Ember.get @, 'errors'
		for key of errors
			if !errors.hasOwnProperty(key)
				continue
			if recordErrors.add?
				recordErrors.add key, errors[key]
			else
				if _.isArray(errors[key])
					recordErrors.set key, errors[key]
				else
					recordErrors.set key, [errors[key]]
		@_saveWasRejected()
		return
```

Not sure if there are any downsides to this, I guess based on the comments above I’m keeping ember-validations’ `errors` object instead of restoring Ember’s version, and just telling `adapterDidInvalidate` how to work with ember-validations’ version. Will that cause other issues elsewhere?

**Comment by anthonycollini** [comment]
:+1: Any luck talking with the guys from ember-data? Or closer to figuring out what is causing the conflict?

**Comment by rondale-sc** [comment]
This is a problem for us as well.  We ran into this in the 1.11 beta, but reverted assuming this would have been fixed by main release.  Now with the security issue this seems like a pretty big blocker.  I have been looking at this issue and associated issues.  It seems as if ember-data is _not_ to blame.  Though I could be wrong.

The error I'm receiving:

![](http://i.imgur.com/0CEdZfK.png)

And

---
![](http://i.imgur.com/TQYwsU0.png)


Versions:

Ember: 1.11.1
Ember Data: 1.0.0-beta.16.1

I think I'll post this to the emberjs ticket as well.

**Comment by jimmay5469** [comment]
We are also getting this issue.  I thought it was because we were putting our validations hash on the models (against this project's recommendations but seems like a better place to me).  Is this a correct assumption?

We solved this with a different approach, patching _this_ library:
```
Ember.Validations.Errors = DS.Errors.extend({
  unknownProperty: function(property) {
    this.set(property, Ember.makeArray());
    return this.get(property);
  }
});
```
We just made `Ember.Validations.Errors` extend `DS.Errors` instead of `Ember.Object`.  I have no idea what negative side-effects this may have but all our tests are passing with this patch so that gave me some confidence.

I also like @mutewinter's approach of not letting this library override the `errors` property and instead create a `clientErrors` property for it to work with.  I have also had trouble with this library overriding `isValid` in the past too (preventing rollback: https://github.com/dockyard/ember-validations/pull/116), which would also be solved much better by introducing `isClientValid` instead of overriding.

If I were to create a PR to this library introducing `clientErrors` and `isClientValid` it would be a breaking change and require a major release version... is this something this project would be open to or would I be better off just creating my own fork and running off of that?

**Comment by rondale-sc** [comment]
@jimmay5469 I think there was a [PR](https://github.com/dockyard/ember-validations/pull/277) that attempted to just this.  Might be something to check out.

Quick question what were your versions when you fixed with the `DS.Errors.extend` and was that the only change necessary to bypass this error?  This is blocking the security update for us, so I'm mighty curious.  <3

**Comment by jimmay5469** [comment]
@rondale-sc we were on ember-data v1.0.0-beta.16.1 and ember v1.11.1 (and have since upgraded to v1.11.3).  We are on an old 1.x.x version of ember-validations and have it included in our ember-cli project via the vendor folder.  I just placed the snippet I have above in my `app/app.js` file.

If you try this and run into any negative side-effects then please let me know so I can know what to look out for in our project.

**Comment by rondale-sc** [comment]
@jimmay5469 Will do!  Thanks for the quick response.  I'll keep you updated on my end.  :)

**Comment by bcardarella** [comment]
Update on this, I spent some time compiling different commits between a range of good and bad commits of Ember. I was able to track down the issue to when the Registry was decoupled from the Container. During this refactor the ember-resolver stopped being called. This is problematic because ember-validations relies upon the ember-resolver's ability to lookup factories outside of the application's namespace.

I have opened this issue in Ember itself. Let's see where it leads: https://github.com/emberjs/ember.js/issues/10907

**Comment by bcardarella** [comment]
My previous research was incorrect, I was building the container incorrectly in the ember-validations test suite. #284 is green for Ember 1.11 but this still does not address this issue. I have cleared Ember 1.11 as the culprit in this case. Time to move onto Ember Data

**Comment by bcardarella** [comment]
I am not able to recreate this issue.

Can someone please try the master branch of this library and let me know if they are still experiencing the problem? I suspect you will but I want to check.

It would be helpful if I could get a small app that recreates the problem.

**Comment by rondale-sc** [comment]
@bcardarella I found the issue in my application, and it was not ember-validations issue.  I was also unable to recreate this error.

**Comment by bcardarella** [comment]
@rondale-sc strange as the repo is passing under 1.11 rght now

**Comment by rondale-sc** [comment]
@bcardarella I mean the issue that I identified in my project.  It was related to a jQuery plugin that we were wrapping deleting a DOM node.  Deleting this node cause an error in Morph between 1.10 and 1.11.  Something about morphs wrapping views in 1.10 and referencing the view directly in 1.11 (though my understanding of this is limited)

I mistook this for the issue from the OP.  Sorry for the confusion, and for not updating my comments here earlier.

**Comment by darrenrogan** [comment]
http://emberjs.jsbin.com/qodejisuxe/4/edit?html,js,console,output

I've run into an issue with the Ember Validation (Replacing the DS.Errors hash is no longer passing the method calls like clear() through). Here is an example; this seems to be relevant to this issue as it only started when I upgraded to 1.11.3 a few days ago.

**Comment by bcardarella** [comment]
@rwjblue can you check out the above jsbin? I have confirmed that if you swap out 1.11.3 for 1.10.0 the code works. (up until the point it attempts to hit an api that doesn't exist, but that is to be expected here)

**Comment by szachara** [comment]
Now I'm debugging this problem, I can confirm, that ember-validations overwrites DS.Errors instance at model.errors property, so whole this implementation and code https://github.com/emberjs/data/blob/v1.0.0-beta.16.1/packages/ember-data/lib/system/model/errors.js is lost.

![ds errors-overwrited](https://cloud.githubusercontent.com/assets/86900/7500330/4978fd60-f42d-11e4-9998-33cd24f35cb0.png)


This problem can be reproduced easily, occurs when i'm using ActiveModelAdapter ( or extended RestAdapater - i describe this few lines below ), important is this code https://github.com/emberjs/data/blob/v1.0.0-beta.16.1/packages/activemodel-adapter/lib/system/active-model-adapter.js#L124, which is not implemented in RestAdapter as is described here http://emberjs.com/api/data/classes/DS.InvalidError.html at bottom of the page.

Error occurs, when POST or PUT data are invalid on my rest server and rest server responses with status code 422 with body structure, which is described here http://emberjs.com/api/data/classes/DS.Errors.html.
After that, ActiveModelAdapter throwes / raise DS.InvalidError and DS.Model tries to add this errors to model.errors object at this line https://github.com/emberjs/data/blob/v1.0.0-beta.16.1/packages/ember-data/lib/system/model/model.js#L1131

**Comment by koryteg** [comment]
has this been fixed in ember 1.12, ember data update? I just bumped to 2.0.0-alpha.4 of ember-validations and I am still getting `recordErrors.add is not a function
    at Ember.Object.extend.adapterDidInvalidate (model.js:1085)`

**Comment by bcardarella** [comment]
@koryteg ember-data integration has not yet been resolved. The alpha 4 bump was to resolve deprecation warnings affecting other users

**Comment by indirect** [comment]
So it's still impossible to use ember-validations with ember-data version 1.11 or newer? :/

**Comment by ryanlitalien** [comment]
Bummer bump... +1 for ember-data 2.x

**Comment by nanuxbe** [comment]
For those interested in using current ember-validations with ember 1.13 and 1.13.15, here is a quick solution (which is clearly not perfect as it doesn't take advantage of `DS.Errors`) which is to use a custom store

```javascript
import Ember from 'ember';
import DS from 'ember-data';

export default DS.Store.extend({
  recordWasInvalid: function (internalModel, errors) {
    console.log(internalModel);
    let record = internalModel.getRecord();
    let recordErrors = record.get('errors');
    let key;
    for (key in errors) {
      if (!errors.hasOwnProperty(key)) {
        continue;
      }
      if (recordErrors.add) {
        recordErrors.add(key, errors[key]);
      } else {
        if (Ember.isArray(errors[key])) {
          recordErrors.set(key, errors[key]);
        } else {
          recordErrors.set(key, [errors[key]]);
        }
      }
    }
    internalModel._saveWasRejected();
  }
});
```

For Ember 2.x @GeoffreyBooth 's solution should work if you reopen `DS.InternalModel` instead of `DS.Model` (same side-effect, it doesn't take advantage of `DS.Errors`)

**Comment by MaksimBurnin** [comment]
A monkey-patch for Ember Data 2.2.0, use at your own risk
```javascript
import Ember from 'ember';
import DS from 'ember-data';

export function initialize() {
  DS.InternalModel.prototype.addErrorMessageToAttribute = function(attribute, message) {
    var record = this.getRecord();
    var errors = Ember.get(record, 'errors');

    if (errors._add != null) {
      errors._add(attribute, message);
    }else{
      errors.set(attribute, Ember.isArray(message) ? message : [message]);
    }
  };
}

export default {
  name: 'model-errors-monkey-patch',
  initialize
};
```

**Comment by Forster-Groux** [comment]
Validations work well if you put them in the controller, but if you put them on models, server-side errors failed to be added.

**Comment by martndemus** [comment]
Ember 1.11 is now supported.
